# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0002_student2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student2',
            name='student1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user2.Student1'),
            preserve_default=False,
        ),
    ]
